packages:
  - 'plugins/*'
allowBuilds:
  esbuild: true
storeDir: /tmp/pnpm-store
autoInstallPeers: true
strictPeerDependencies: false
minimumReleaseAgeExclude:
  - '@deepseek-ai/cosmokit@1.8.5'
  - '@deepseek-ai/dsh-client-ui-primitives@0.1.7-rc.1'
  - '@deepseek-ai/schemastery@3.18.4'
