/**
 * official.ts —— 官方样式表的原始 alias / specific token 值（无操作覆盖用）。
 *
 * 来源：dsh-client-ui-theme 的 body 与 body[data-ds-dark-theme] 规则。
 * 覆盖层的对侧 scheme 分支填这些 var() 引用 —— 用户在官方亮/暗之间切换时，
 * 覆盖层自动呈现对侧官方原值，等于「没有覆盖」。
 *
 * 原实现：dsh-custom-ui/client.js 内联常量，值逐字保留（仅从 factory 提到模块级）。
 *
 * @module @dshp/web-style/client
 */
import type { TokenMap } from './types.js';

/** 官方亮色主题的 alias token 原值。 */
export const OFFICIAL_LIGHT: TokenMap = {
  '--dsw-alias-bg-base': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-bg-layer-1': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-bg-layer-2': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-bg-layer-3': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-bg-mask-1': '#0000003d',
  '--dsw-alias-bg-mask-2': '#0000001f',
  '--dsw-alias-bg-mask-3': '#0000007a',
  '--dsw-alias-bg-mask-photo': '#000000e0',
  '--dsw-alias-bg-mask-drop': '#ffffffb3',
  '--dsw-alias-bg-module-platform': 'var(--dsw-static-neutral-bluish-60)',
  '--dsw-alias-bg-multi-select': 'var(--dsw-static-neutral-bluish-60)',
  '--dsw-alias-bg-overlay': 'var(--dsw-static-neutral-bluish-150)',
  '--dsw-alias-bg-skeleton': '#0000000a',
  '--dsw-alias-border-inverted2': '#0000',
  '--dsw-alias-border-inverted': '#0000',
  '--dsw-alias-border-l1': '#0000000a',
  '--dsw-alias-border-l2-darkmode-thin': '#0000001a',
  '--dsw-alias-border-l2': '#0000001a',
  '--dsw-alias-border-l3': '#0000001f',
  '--dsw-alias-border-l4': '#00000029',
  '--dsw-alias-brand-primary-invert': 'var(--dsw-static-neutral-bluish-1000)',
  '--dsw-alias-brand-primary': 'var(--dsw-static-neutral-bluish-1000)',
  '--dsw-alias-brand-text': 'var(--dsw-static-neutral-bluish-1000)',
  '--dsw-alias-button-contrast-fill': 'var(--dsw-static-neutral-bluish-700)',
  '--dsw-alias-button-elevated-fill': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-button-floating-fill': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-button-floating-hover': 'var(--dsw-static-neutral-bluish-75)',
  '--dsw-alias-button-ghost-active-border': 'var(--dsw-static-neutral-bluish-500)',
  '--dsw-alias-button-ghost-active-fill': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-button-ghost-active-hover': 'var(--dsw-static-neutral-bluish-150)',
  '--dsw-alias-button-info-fill': 'var(--dsw-static-deepseek-500)',
  '--dsw-alias-button-info-hover': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-button-primary-dimmed': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-button-primary-fill': 'var(--dsw-alias-brand-primary)',
  '--dsw-alias-button-primary-hover': 'var(--dsw-static-neutral-bluish-750)',
  '--dsw-alias-button-tool-bar-fill-invisible': '#1f1f1f5c',
  '--dsw-alias-button-tool-bar-fill': '#54555780',
  '--dsw-alias-button-tool-bar-hover': '#54555799',
  '--dsw-alias-interactive-bg-active': '#2631481a',
  '--dsw-alias-interactive-bg-hover-accent': '#26314824',
  '--dsw-alias-interactive-bg-hover-danger': '#ec13130d',
  '--dsw-alias-interactive-bg-hover-solid': 'var(--dsw-static-neutral-bluish-75)',
  '--dsw-alias-interactive-bg-hover': '#2631480f',
  '--dsw-alias-label-caption': 'var(--dsw-static-neutral-bluish-400)',
  '--dsw-alias-label-dimmed': 'var(--dsw-static-neutral-bluish-200)',
  '--dsw-alias-label-primary-bluish': 'var(--dsw-static-blue-900)',
  '--dsw-alias-label-primary-dimmed': 'var(--dsw-static-neutral-bluish-950)',
  '--dsw-alias-label-primary-foreground': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-label-primary-inverted': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-label-primary': 'var(--dsw-static-neutral-bluish-1000)',
  '--dsw-alias-label-secondary': 'var(--dsw-static-neutral-bluish-700)',
  '--dsw-alias-label-tertiary': 'var(--dsw-static-neutral-bluish-600)',
  '--dsw-alias-markdown-citation': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-markdown-code-block-banner': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-alias-markdown-code-block': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-alias-markdown-code-segment-selected': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-markdown-code-segment-unselected': 'var(--dsw-static-neutral-bluish-75)',
  '--dsw-alias-markdown-inline-code': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-markdown-placeholder': 'var(--dsw-static-neutral-bluish-60)',
  '--dsw-alias-markdown-tag': 'var(--dsw-static-neutral-bluish-75)',
  '--dsw-alias-scrollbar-bg-l1': 'var(--dsw-static-neutral-200)',
  '--dsw-alias-scrollbar-bg-l2': 'var(--dsw-static-neutral-200)',
  '--dsw-alias-scrollbar-hover-l1': 'var(--dsw-static-neutral-300)',
  '--dsw-alias-scrollbar-hover-l2': 'var(--dsw-static-neutral-300)',
  '--dsw-alias-state-business-primary': 'var(--dsw-static-deepseek-500)',
  '--dsw-alias-state-business-tertiary': 'var(--dsw-static-deepseek-100)',
  '--dsw-alias-state-error-primary': 'var(--dsw-static-red-600)',
  '--dsw-alias-state-error-secondary': 'var(--dsw-static-red-400)',
  '--dsw-alias-state-success-primary': 'var(--dsw-static-green-500)',
  '--dsw-alias-state-success-secondary': 'var(--dsw-static-green-400)',
  '--dsw-alias-state-success-tertiary': 'var(--dsw-static-green-100)',
  '--dsw-alias-state-warn-label': 'var(--dsw-static-amber-600)',
  '--dsw-alias-state-warn-primary': 'var(--dsw-static-amber-500)',
  '--dsw-alias-state-warn-secondary': 'var(--dsw-static-amber-400)',
  '--dsw-alias-state-warn-tertiary': 'var(--dsw-static-amber-100)',
  '--dsw-alias-toast-bg': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-tooltip-bg': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-specific-bubble-highlight': 'var(--dsw-static-deepseek-200)',
  '--dsw-specific-bubble': 'var(--dsw-static-deepseek-50)',
  '--dsw-specific-input-major': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-specific-login-input': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-specific-menu': 'var(--dsw-alias-bg-layer-3)',
  '--dsw-specific-selector': 'var(--dsw-static-neutral-bluish-60)',
  '--dsw-specific-sidebar-fill': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-specific-sidebar-nav-item-active-accent': 'var(--dsw-static-deepseek-100)',
  '--dsw-specific-sidebar-nav-item-active': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-specific-sidebar-nav-item-hover': 'var(--dsw-static-neutral-bluish-75)',
  '--dsw-specific-tip': 'var(--dsw-static-neutral-bluish-60)',
};

/** 官方暗色主题的 alias token 原值。 */
export const OFFICIAL_DARK: TokenMap = {
  '--dsw-alias-bg-base': 'var(--dsw-static-neutral-bluish-950)',
  '--dsw-alias-bg-layer-1': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-alias-bg-layer-2': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-alias-bg-layer-3': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-bg-mask-1': '#ffffff1a',
  '--dsw-alias-bg-mask-2': '#ffffff0f',
  '--dsw-alias-bg-mask-3': '#ffffff4d',
  '--dsw-alias-bg-mask-photo': '#000000e0',
  '--dsw-alias-bg-mask-drop': '#ffffff33',
  '--dsw-alias-bg-module-platform': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-alias-bg-multi-select': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-alias-bg-overlay': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-alias-bg-skeleton': '#ffffff0d',
  '--dsw-alias-border-inverted2': '#0000',
  '--dsw-alias-border-inverted': '#0000',
  '--dsw-alias-border-l1': '#ffffff12',
  '--dsw-alias-border-l2-darkmode-thin': '#ffffff14',
  '--dsw-alias-border-l2': '#ffffff1f',
  '--dsw-alias-border-l3': '#ffffff29',
  '--dsw-alias-border-l4': '#ffffff33',
  '--dsw-alias-brand-primary-invert': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-brand-primary': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-brand-text': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-button-contrast-fill': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-button-elevated-fill': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-alias-button-floating-fill': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-alias-button-floating-hover': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-button-ghost-active-border': 'var(--dsw-static-neutral-bluish-600)',
  '--dsw-alias-button-ghost-active-fill': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-alias-button-ghost-active-hover': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-button-info-fill': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-button-info-hover': 'var(--dsw-static-deepseek-300)',
  '--dsw-alias-button-primary-dimmed': 'var(--dsw-static-deepseek-600)',
  '--dsw-alias-button-primary-fill': 'var(--dsw-alias-brand-primary)',
  '--dsw-alias-button-primary-hover': 'var(--dsw-static-deepseek-450)',
  '--dsw-alias-button-tool-bar-fill-invisible': '#54555799',
  '--dsw-alias-button-tool-bar-fill': '#54555780',
  '--dsw-alias-button-tool-bar-hover': '#54555799',
  '--dsw-alias-interactive-bg-active': '#5686fe29',
  '--dsw-alias-interactive-bg-hover-accent': '#5686fe33',
  '--dsw-alias-interactive-bg-hover-danger': '#f25a5a33',
  '--dsw-alias-interactive-bg-hover-solid': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-interactive-bg-hover': '#5686fe1f',
  '--dsw-alias-label-caption': 'var(--dsw-static-neutral-bluish-500)',
  '--dsw-alias-label-dimmed': 'var(--dsw-static-neutral-bluish-600)',
  '--dsw-alias-label-primary-bluish': 'var(--dsw-static-blue-100)',
  '--dsw-alias-label-primary-dimmed': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-alias-label-primary-foreground': 'var(--dsw-static-neutral-bluish-950)',
  '--dsw-alias-label-primary-inverted': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-label-primary': 'var(--dsw-static-neutral-bluish-00)',
  '--dsw-alias-label-secondary': 'var(--dsw-static-neutral-bluish-100)',
  '--dsw-alias-label-tertiary': 'var(--dsw-static-neutral-bluish-600)',
  '--dsw-alias-markdown-citation': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-markdown-code-block-banner': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-alias-markdown-code-block': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-alias-markdown-code-segment-selected': 'var(--dsw-static-neutral-bluish-50)',
  '--dsw-alias-markdown-code-segment-unselected': 'var(--dsw-static-neutral-bluish-700)',
  '--dsw-alias-markdown-inline-code': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-markdown-placeholder': 'var(--dsw-static-neutral-bluish-700)',
  '--dsw-alias-markdown-tag': 'var(--dsw-static-neutral-bluish-700)',
  '--dsw-alias-scrollbar-bg-l1': 'var(--dsw-static-neutral-400)',
  '--dsw-alias-scrollbar-bg-l2': 'var(--dsw-static-neutral-500)',
  '--dsw-alias-scrollbar-hover-l1': 'var(--dsw-static-neutral-500)',
  '--dsw-alias-scrollbar-hover-l2': 'var(--dsw-static-neutral-600)',
  '--dsw-alias-state-business-primary': 'var(--dsw-static-deepseek-400)',
  '--dsw-alias-state-business-tertiary': 'var(--dsw-static-deepseek-100)',
  '--dsw-alias-state-error-primary': 'var(--dsw-static-red-400)',
  '--dsw-alias-state-error-secondary': 'var(--dsw-static-red-400)',
  '--dsw-alias-state-success-primary': 'var(--dsw-static-green-400)',
  '--dsw-alias-state-success-secondary': 'var(--dsw-static-green-400)',
  '--dsw-alias-state-success-tertiary': 'var(--dsw-static-green-100)',
  '--dsw-alias-state-warn-label': 'var(--dsw-static-amber-400)',
  '--dsw-alias-state-warn-primary': 'var(--dsw-static-amber-400)',
  '--dsw-alias-state-warn-secondary': 'var(--dsw-static-amber-400)',
  '--dsw-alias-state-warn-tertiary': 'var(--dsw-static-amber-100)',
  '--dsw-alias-toast-bg': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-alias-tooltip-bg': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-specific-bubble-highlight': 'var(--dsw-static-deepseek-700)',
  '--dsw-specific-bubble': 'var(--dsw-static-deepseek-800)',
  '--dsw-specific-input-major': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-specific-login-input': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-specific-menu': 'var(--dsw-alias-bg-layer-3)',
  '--dsw-specific-selector': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-specific-sidebar-fill': 'var(--dsw-static-neutral-bluish-900)',
  '--dsw-specific-sidebar-nav-item-active-accent': 'var(--dsw-static-deepseek-700)',
  '--dsw-specific-sidebar-nav-item-active': 'var(--dsw-static-neutral-bluish-800)',
  '--dsw-specific-sidebar-nav-item-hover': 'var(--dsw-static-neutral-bluish-850)',
  '--dsw-specific-tip': 'var(--dsw-static-neutral-bluish-700)',
};
